### ISSUE TITLE
Is it possible to write a CtrlP matcher with this?

### ISSUE THREAD

**Issue by lervag** [raghur/fruzzy#1]
Based on the description, I suspect it should be possible to write a CtrlP matcher with this as a backend. Do you think this is possible?

See also [ctrlp-py-matcher](https://github.com/FelikZ/ctrlp-py-matcher) and [cpsm](https://github.com/nixprime/cpsm).

**Comment by raghur** [comment]
Of course... It should be.
I used to use CPSM quite a while back but don't anymore

Do you want to contribute a PR?

**Comment by lervag** [comment]
Yes, I might, but I need some time to understand how to do it. If you already have some ideas it would be helpful to hear them. FYI, I have a lot of experience with Vim plugins, but none with developing within CtrlP or similar types of plugins.

**Comment by raghur** [comment]
That's great! My vimscript fu is pretty bad. 
I don't know what sort of interface CtrlP matcher expects - but you'd have to find that out.
After that, it's a matter of:

1. make sure `fruzzy.py` or `fruzzy_mod` is loaded and can be imported (based on whether user wants to load native mod)
2. [pure python] call def scoreMatches(query, candidates, limit, key=None, ispath=True):
3. [native] - call scoreMatchesStr (same params as above - other than there is no key func)
4. Take a look at `fruzzy_test.py` for a wrapper that calls one of the above based on pref
```
def scoreMatchesProxy(q, c, limit, key=None, ispath=True):
    if useNative:
        idxArr = scoreMatchesStr(q, (key(x) for x in c), limit, ispath)
        results = []
        for i in idxArr:
            results.append((c[i[0]], i[1]))
        return results
    else:
        return scoreMatches(q, c, limit, key, ispath)
```
5. The python version takes any sequence and a key func to extract the string to search. The native version only takes a string sequence and returns a list of tuples (matchindex, score) in order of highest relevance.
6. do any massaging reqd for ctrlp and send it back

**Comment by lervag** [comment]
It seems cspm is a good inspiration for how to do this. I've started to work on it, but it will probably take some time. I need to understand how to properly connect vimscript to python (I think we're almost there), and then how to import the fruzzy package from the ctrlp.py file and so on. I'm opening a PR so you can see how things develop.

**Comment by lervag** [comment]
Ok, I've done some more work, see #7. The initial goal is to have the pure python version to work first. I'll continue the discussion here for now. Some questions:

1. What is `key` in `scoreMatches`?
2. It would be nice to also highlight the matching strings. Do you have any idea how to achieve this? With `cpsm`, the matcher returns a list of regexes...
