### ISSUE TITLE
fruzzy install fail

### ISSUE THREAD

**Issue by numbcoder** [raghur/fruzzy#12]
platform: macOS 10.14
neovim: 0.3.1
Python: 3.7.0
Error stack:
```
Error detected while processing function fruzzy#install[1]..provider#python3#Call:
line   18:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/seekr/.vim/bundle/fruzzy/python3/fruzzy_installer.py", line 34, in install
    print("fruzzy: downloading %s to %s" % (asset['browser_download_url'],
TypeError: 'NoneType' object is not subscriptable
```

Although it downloads native mod fail, it still work well for me.
Thanks for your work! Awesome matcher

**Comment by raghur** [comment]
Ah - you're on a Mac.. I'm unable to provide prebuilt binaries for mac (see #9 ). I'm looking for ways to cross compile fruzzy for mac but am a little tied up right now to investigate.

However, compiling from source is really easy - you just need nim 0.19 and then follow the instructions on the readme.

**Comment by raghur** [comment]
@numbcoder - I've tried out cross compiling from linux to osx. Here's the binary - would you be able to test on your mac? If it works, then I'll add it to the release assets.

https://gofile.io/?c=S4zrSe

You need to rename it to `fruzzy_mod.so` and put it in the `/path/to/fruzzy/rplugin/python3` folder. After that restart vim/nvim. If you invoke denite and filter, you should see a log message in `:messages` that prints out the version of the native mod and have a snappier experience

Let me know if it works.

**Comment by raghur** [comment]
@numbcoder  - Thanks for the confirmation. I now have a decent cross compilation setup. Will upload the binary to the releases so that install function works properly.
