### ISSUE TITLE
Crash on dein#recache_runtimepath()

### ISSUE THREAD

**Issue by Luxed** [raghur/fruzzy#18]
When doing `call dein#recache_runtimepath()`, I get this error:
```
[dein] "C:/Users/cbrunel/AppData/Local/nvim/dein/.cache/init.vim/.dein" cannot be removed.
[dein] cmdline is "rmdir /S /Q "C:\\Users\\cbrunel\\AppData\\Local\\nvim\\dein\\.cache\\init.vim\\.dein"".
```

After trying to remove it with PowerShell, I saw that the file `fruzzy_mod.pyd` is still in use and therefore cannot be deleted.
Is there any way to get over this issue?

**Comment by Shougo** [comment]
It is the feature of Windows.
Windows cannot update DLL when DLL is loaded.

You should specify `"merged": 0` in dein configuration.

```vim
call dein#add('raghur/fruzzy', {'merged': 0})
```

**Comment by Luxed** [comment]
> It is the feature of Windows.
> Windows cannot update DLL when DLL is loaded.
> 
> You should specify `"merged": 0` in dein configuration.
> 
> ```viml
> call dein#add('raghur/fruzzy', {'merged': 0})
> ```

Thank you for that, it works perfectly!
