### ISSUE TITLE
Binary not working on Mac

### ISSUE THREAD

**Issue by chemzqm** [raghur/fruzzy#5]
I tried to build myself, here is the file (ziped):

[fruzzy.zip](https://github.com/raghur/fruzzy/files/2433524/fruzzy.zip)

**Comment by raghur** [comment]
I don't have a mac to test. what is the version of the nim compiler? You should be on 0.19+

**Comment by chemzqm** [comment]
The latest one, 0.19.

**Comment by chemzqm** [comment]
You can use https://github.com/tpoechtrager/osxcross for cross compile mac binary on Linux or Cygwin

**Comment by raghur** [comment]
Thanks - I merged your PR once I understood teh context from the PR comment.
