### ISSUE TITLE
OSX build

### ISSUE THREAD

**Issue by raghur** [raghur/fruzzy#9]
Don't have a mac. Need a way to generate OSX binaries for releases

**Comment by raghur** [comment]
https://github.com/tpoechtrager/osxcross has been suggested but even this possibly requires a mac initially for the SDK? not sure.

**Comment by mikesale** [comment]
I'm willing to throw myself at this one to generate the package.

**Comment by mikesale** [comment]
ran the pytest as instructed and it runs zero tests

**Comment by raghur** [comment]
Fixed in d612ae18d0d14b08a6ff7cca73140334fbfda2d6
